import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useAuth } from '../hooks/useAuth';
import { useNavigate } from 'react-router-dom';
const Dashboard = () => {
    const { user, logout } = useAuth();
    const navigate = useNavigate();
    const handleLogout = async () => {
        await logout();
        navigate('/login');
    };
    return (_jsxs("div", { className: "min-h-screen bg-gray-50", children: [_jsx("header", { className: "bg-white shadow", children: _jsxs("div", { className: "mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8 flex justify-between items-center", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-3xl font-bold tracking-tight text-gray-900", children: "Dashboard" }), _jsxs("p", { className: "mt-1 text-sm text-gray-600", children: ["Bienvenido, ", user?.name] })] }), _jsx("button", { onClick: handleLogout, className: "inline-flex items-center justify-center rounded-md border border-transparent bg-red-600 py-2 px-4 text-sm font-medium text-white hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2", children: "Cerrar Sesi\u00F3n" })] }) }), _jsx("main", { className: "mx-auto max-w-7xl py-6 sm:px-6 lg:px-8", children: _jsxs("div", { className: "px-4 py-6 sm:px-0", children: [_jsx("div", { className: "rounded-lg bg-white shadow", children: _jsxs("div", { className: "px-4 py-5 sm:p-6", children: [_jsx("h3", { className: "text-lg font-medium leading-6 text-gray-900", children: "Informaci\u00F3n del Usuario" }), _jsxs("dl", { className: "mt-5 grid grid-cols-1 gap-5 sm:grid-cols-2", children: [_jsxs("div", { className: "overflow-hidden rounded-lg bg-gray-50 px-4 py-5 shadow sm:p-6", children: [_jsx("dt", { className: "truncate text-sm font-medium text-gray-500", children: "Email" }), _jsx("dd", { className: "mt-1 text-3xl font-semibold tracking-tight text-gray-900", children: user?.email })] }), _jsxs("div", { className: "overflow-hidden rounded-lg bg-gray-50 px-4 py-5 shadow sm:p-6", children: [_jsx("dt", { className: "truncate text-sm font-medium text-gray-500", children: "Rol" }), _jsx("dd", { className: "mt-1 text-3xl font-semibold tracking-tight text-gray-900", children: _jsx("span", { className: `inline-flex items-center rounded-full px-3 py-1 text-sm font-medium ${user?.role === 'ADMIN'
                                                                ? 'bg-red-100 text-red-800'
                                                                : user?.role === 'MANAGER'
                                                                    ? 'bg-yellow-100 text-yellow-800'
                                                                    : 'bg-green-100 text-green-800'}`, children: user?.role }) })] }), user?.sedeId && (_jsxs("div", { className: "overflow-hidden rounded-lg bg-gray-50 px-4 py-5 shadow sm:p-6", children: [_jsx("dt", { className: "truncate text-sm font-medium text-gray-500", children: "ID Sede" }), _jsx("dd", { className: "mt-1 text-3xl font-semibold tracking-tight text-gray-900", children: user.sedeId })] }))] })] }) }), _jsx("div", { className: "mt-8 rounded-lg bg-blue-50 p-6 border border-blue-200", children: _jsxs("div", { className: "flex", children: [_jsx("svg", { className: "h-5 w-5 text-blue-400", viewBox: "0 0 20 20", fill: "currentColor", children: _jsx("path", { fillRule: "evenodd", d: "M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z", clipRule: "evenodd" }) }), _jsxs("div", { className: "ml-3", children: [_jsx("h3", { className: "text-sm font-medium text-blue-900", children: "Pr\u00F3ximas Funcionalidades" }), _jsx("p", { className: "mt-2 text-sm text-blue-700", children: "En los pr\u00F3ximos sprints se a\u00F1adir\u00E1n: Gesti\u00F3n de usuarios, Gesti\u00F3n de sedes, Gesti\u00F3n de turnos, Calendario, Permutas de turnos, Inventario y N\u00F3minas." })] })] }) })] }) })] }));
};
export default Dashboard;
//# sourceMappingURL=Dashboard.js.map